### ISSUE TITLE
Getting error while giving the tag name.

### ISSUE THREAD

**Issue by LakshmiRavali** [tubone24/update_release#127]
I am using this github action like below:
```
updateRelease:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ github.token }}
      TAG_NAME: "5.28.0"
    steps:
    - uses: actions/checkout@v2
    - name: update release
      id: update_release
      uses: tubone24/update_release@v1.0
      with:
        isAppendBody: true
        body: "Testing append" 
```

I am getting below error:
```
RequestError [HttpError]: Not Found
    at /home/runner/work/_actions/tubone24/update_release/v1.0/webpack:/update_release/node_modules/@octokit/request/dist-node/index.js:66:1
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at run (/home/runner/work/_actions/tubone24/update_release/v1.0/webpack:/update_release/src/update-release.js:10:1) {
  name: 'HttpError',
  status: 404,
  headers: {
    'access-control-allow-origin': '*',
    'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset',
    connection: 'close',
    'content-encoding': 'gzip',
    'content-security-policy': "default-src 'none'",
    'content-type': 'application/json; charset=utf-8',
    date: 'Mon, 23 Aug 2021 15:10:50 GMT',
    'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
    server: 'GitHub.com',
    'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
    'transfer-encoding': 'chunked',
    vary: 'Accept-Encoding, Accept, X-Requested-With',
    'x-content-type-options': 'nosniff',
    'x-frame-options': 'deny',
    'x-github-media-type': 'github.v3; format=json',
    'x-github-request-id': '07C2:2B39:32DE0F9:5B73599:6123BA7A',
    'x-ratelimit-limit': '1000',
    'x-ratelimit-remaining': '995',
    'x-ratelimit-reset': '1629733945',
    'x-ratelimit-resource': 'core',
    'x-ratelimit-used': '5',
    'x-xss-protection': '0'
  },
  request: {
    method: 'GET',
    url: 'https://api.github.com/repos/LakshmiRavali/twilio-cli-core/releases/tags/refs/heads/test_branch',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit.js/16.43.2 Node.js/12.13.1 (Linux 5.8; x64)',
      authorization: 'token [REDACTED]'
    },
    request: { hook: [Function: bound bound register], validate: [Object] }
  },
  documentation_url: 'https://docs.github.com/rest/reference/repos#get-a-release-by-tag-name'
}
Error: Not Found
```

**Comment by edalzell** [comment]
I get the same error when using a `RELEASE_ID`, it's trying to get by tag.

**Comment by tubone24** [comment]
@LakshmiRavali 
Thank you for posting the issue.
The error you are encountering indicates that the tag you specified does not exist.
Is your repository which problem is occurring <https://github.com/LakshmiRavali/twilio-cli-core> correct?
I checked and the tag `5.28.0` is not pushed. By the way, `v5.28.0` is pushed.

<img width="509" alt="スクリーンショット 2022-06-12 21 32 49" src="https://user-images.githubusercontent.com/9511227/173233570-d14ab506-c9e1-477b-9c33-b4445bdfbbb2.png">

**Comment by GorlikItsMe** [comment]
I did the same thing and got the same error:

Action:
```yml
      - name: update release
        id: update_release
        uses: tubone24/update_release@v1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: ${{ steps.package-version.outputs.version }}
        with:
          body: test
```
```
steps.package-version.outputs.version -> 1.12.5
```

Error:
```
RequestError [HttpError]: Not Found
    at D:\a\_actions\tubone24\update_release\v1.0\webpack:\update_release\node_modules\@octokit\request\dist-node\index.js:66:1
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at run (D:\a\_actions\tubone24\update_release\v1.0\webpack:\update_release\src\update-release.js:10:1) {
  status: 404,
  headers: {
    'access-control-allow-origin': '*',
    'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset',
    connection: 'close',
    'content-encoding': 'gzip',
    'content-security-policy': "default-src 'none'",
    'content-type': 'application/json; charset=utf-8',
    date: 'Sat, 12 Aug 2023 19:19:38 GMT',
    'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
    server: 'GitHub.com',
    'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
    'transfer-encoding': 'chunked',
    vary: 'Accept-Encoding, Accept, X-Requested-With',
    'x-accepted-github-permissions': 'contents=read',
    'x-content-type-options': 'nosniff',
    'x-frame-options': 'deny',
    'x-github-api-version-selected': '2022-11-28',
    'x-github-media-type': 'github.v3; format=json',
    'x-github-request-id': 'A4D0:4E49:283559E:53025C8:64D7DB4A',
    'x-ratelimit-limit': '1000',
    'x-ratelimit-remaining': '974',
    'x-ratelimit-reset': '1691869372',
    'x-ratelimit-resource': 'core',
    'x-ratelimit-used': '26',
    'x-xss-protection': '0'
  },
  request: {
    method: 'GET',
    url: 'https://api.github.com/repos/Nosvoid/nosvoid-launcher/releases/tags/refs/heads/main',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit.js/16.43.2 Node.js/16.16.0 (Windows 10; x64)',
      authorization: 'token [REDACTED]'
    },
    request: { hook: [Function: bound bound register], validate: [Object] }
  },
  documentation_url: 'https://docs.github.com/rest/releases/releases#get-a-release-by-tag-name'
}
```

im 100% sure i put correct TAG_NAME

Also my repo is private
