### ISSUE TITLE
'name' cannot be null

### ISSUE THREAD

**Issue by Snuffsis** [tubone24/update_release#541]
I am having an issue where it is complaining about the name and that it cannot be null?

the action looks like the one you are using in your twitter project as an example. But still no success.

This is the github action log:

```
Run tubone[2](https://github.com/xxxxx/yyyyy/runs/7764068139?check_suite_focus=true#step:4:2)4/update_release@v1.[3](https://github.com/xxxxx/yyyyy/runs/7764068139?check_suite_focus=true#step:4:3).1
  with:
    body: ## 🐛 Bugfixes
  - add id to update action
  env:
    GITHUB_TOKEN: ***
Updating release with tag : '0.0.5-beta69'
Got release info: '7[4](https://github.com/xxxxx/yyyyy/runs/7764068139?check_suite_focus=true#step:4:4)081828', null, 'https://github.com/xxxxx/yyyyy/releases/tag/0.0.[5](https://github.com/xxxxx/yyyyy/runs/7764068139?check_suite_focus=true#step:4:5)-beta[6](https://github.com/xxxxx/yyyyy/runs/7764068139?check_suite_focus=true#step:4:6)9', 'https://uploads.github.com/repos/xxxxx/yyyyy/releases/[7](https://github.com/xxxxx/yyyyy/runs/7764068139?check_suite_focus=true#step:4:8)40[8](https://github.com/xxxxx/yyyyy/runs/7764068139?check_suite_focus=true#step:4:9)1828/assets{?name,label},'
Body: 

## Changes:

* 05afa[9](https://github.com/xxxxx/yyyyy/runs/7764068139?check_suite_focus=true#step:4:10)dad2dbcfae06ce26b8893aa454d82a0918 fix: add id to update action

This list of changes was [auto generated](https://dev.azure.com/xxxxx/yyyyy/_build/results?buildId=78&view=logs).
Draft: false, Prerelease: false
Error: 'name' cannot be null
```

And the yml file:

```
name: Create preview package

on:
  release:
    types: [created]

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create changelog text
        id: changelog
        uses: loopwerk/tag-changelog@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config_file: .github/custom-changelog-config.js

      - name: Update release notes
        id: update_release
        uses: tubone24/update_release@v1.3.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body: ${{ steps.changelog.outputs.changes }}
```
